### ISSUE TITLE
Patient Login API endpoint

### ISSUE THREAD

**Issue by Kisuk3S4m** [Kisuk3S4m/jungle-ehr-api#2]
**As** already registered patient,
**I want** to log in to the system
**So** I want access to the system.

### Details and assumptions
- Users must provide an `email` and `password` related to their registered account.
- If a user provides an incorrect `email` or `password`, this user cannot log in.
- The user cannot log in for the second time after one successful login.
- Use **JWT** for authentication, which includes issuing a token on successful login and validating this token for subsequent requests.
- Limit the number of login attempts to prevent **brute-force** attacks.

### Acceptance Criteria
```gherkin
Given a registered user with the email "user@example.com" and password "correctpassword"
When the user attempts to log in with the email "user@example.com" and password "correctpassword"
Then the user should receive a JWT token
And the user should be logged in successfully
```

```gherkin
Given a registered user with the email "user@example.com" and password "correctpassword"
When the user attempts to log in with the email "user@example.com" and password "wrongpassword"
Then the user should not be logged in
And the user should receive an error message "Invalid email or password"
```

```gherkin
Given a registered user with the email "user@example.com" and password "correctpassword"
When the user attempts to log in with the email "wronguser@example.com" and password "correctpassword"
Then the user should not be logged in
And the user should receive an error message "Invalid email or password"
```

```gherkin
Given a registered user with the email "user@example.com" and password "correctpassword"
And the user has attempted to log in with incorrect credentials 5 times
When the user attempts to log in again
Then the user should not be logged in
And the user should receive an error message "Maximum login attempts exceeded, please try again later"
```

```gherkin
Given a registered user with the email "user@example.com" and password "correctpassword"
And the user has already logged in successfully
When the user attempts to log in again with the same credentials
Then the user should not be logged in
And the user should receive an error message "User already logged in"
```

### Subtasks
- [ ] Create a login API endpoint that accepts `email` and `password`.
- [ ] Validate the provided credentials against the registered user database.
- [ ] Generate and return a JWT token on successful login.
- [ ] Implement error handling for incorrect email or password.
- [ ] Implement a mechanism to track login attempts and lock the account after a specified number of failed attempts.
- [ ] Ensure a mechanism to prevent a second login after a successful login.
- [ ] Write unit and integration tests for the login functionality.
