### ISSUE TITLE
Patient Profile View Endpoint

### ISSUE THREAD

**Issue by Kisuk3S4m** [Kisuk3S4m/jungle-ehr-api#4]
**As** logged-in patient,
**I want** to view my account profile,
**So** I can review personal information and I could modify them using another endpoint.

### Details and assumptions
- Users must provide JWT access and CSRF tokens to the endpoint.
- The endpoint should reject the user from operating if they have invalid or missing tokens.
- The endpoint should show users' personal information if the tokens are both valid.
- Users' personal information must be shown in JSON format.
- Users' passwords should not be shown, they must be masked using 8 asterisks(********).
 
### Acceptance Criteria
```gherkin
Given the user is logged in
And the user provides valid JWT access and CSRF tokens
When the user requests to view their account profile
Then the system should return the user's personal information in JSON format
And the password should be masked with 8 asterisks (********)
```

```gherkin
Given the user is logged in
And the user provides an invalid JWT access token
When the user requests to view their account profile
Then the system should reject the request
And the system should return an error message indicating an invalid token
```

```gherkin
Given the user is logged in
And the user provides an invalid CSRF token
When the user requests to view their account profile
Then the system should reject the request
And the system should return an error message indicating an invalid token
```

```gherkin
Given the user is logged in
And the user does not provide a JWT access token
When the user requests to view their account profile
Then the system should reject the request
And the system should return an error message indicating a missing token
```

```gherkin
Given the user is logged in
And the user does not provide a CSRF token
When the user requests to view their account profile
Then the system should reject the request
And the system should return an error message indicating a missing token
```

### Subtasks
- [ ] **Define the Endpoint**
  - [ ] Create the endpoint to view the account profile.
  - [ ] Ensure the endpoint requires JWT access and CSRF tokens.
- [ ] **Token Validation**
  - [ ] Implement JWT access token validation.
  - [ ] Implement CSRF token validation.
- [ ] **Fetch User Information**
  - [ ] Retrieve the user's personal information from the database
  - [ ] Mask the user's password with 8 asterisks (********).
- [ ] **Response formatting**
  - [ ] Format the user's personal information in JSON.
  - [ ] Ensure the masked password is included in the JSON response.
- [ ] **Error Handling**
  - [ ] Implement error handling for invalid or missing tokens.
  - [ ] Ensure appropriate error messages are returned for each type of invalid or missing token.
- [ ] **Testing**
  - [ ] Write unit tests for the endpoint
  - [ ] Write integration tests for the entire process, including token validation and information retrieval.
  - [ ] Test all acceptance criteria scenarios to ensure compliance.
