### ISSUE TITLE
Patient Profile Edit

### ISSUE THREAD

**Issue by Kisuk3S4m** [Kisuk3S4m/jungle-ehr-api#5]
**As** logged-in patient,
**I want** to edit my account profile information
**So** I can edit personal information if something is incorrect.

### Details and assumptions
- Users must provide JWT access and CSRF tokens to the endpoint.
- The endpoint should reject the user from operating if they have invalid or missing tokens.
- Users must provide editing information
- The endpoint should show accept editing information if this information is valid(e.g. unique email, unique fiscal code, valid birth of date format).
- The endpoint should reject editing information if this information is invalid(e.g. email already taken, fiscal code already taken, invalid date of birth format).
- Users' personal information must be shown in JSON format.
- Users' should not be allowed to modify passwords: password modification operation should be performed in another specific endpoint.

### Acceptance Criteria
```gherkin
Given the user is logged in
And the user provides valid JWT access and CSRF tokens
And the user provides valid editing information
When the user requests to edit their account profile
Then the system should update the user's personal information
And the system should return the updated personal information in JSON format
```

```gherkin
Given the user is logged in
And the user provides an invalid JWT access token
When the user requests to edit their account profile
Then the system should reject the request
And the system should return an error message indicating an invalid token
```

```gherkin
Given the user is logged in
And the user provides an invalid CSRF token
When the user requests to edit their account profile
Then the system should reject the request
And the system should return an error message indicating an invalid token
```

```gherkin
Given the user is logged in
And the user does not provide a JWT access token
When the user requests to edit their account profile
Then the system should reject the request
And the system should return an error message indicating a missing token
```

```gherkin
Given the user is logged in
And the user does not provide a CSRF token
When the user requests to edit their account profile
Then the system should reject the request
And the system should return an error message indicating a missing token
```

```gherkin
Given the user is logged in
And the user provides valid JWT access and CSRF tokens
And the user provides invalid editing information
When the user requests to edit their account profile
Then the system should reject the request
And the system should return an error message indicating the invalid data
```

```gherkin
Given the user is logged in
And the user provides valid JWT access and CSRF tokens
And the user does not provide password modification information
When the user requests to edit their account profile
Then the system should update the user's personal information
And the system should return the updated personal information in JSON format
And the system should not show the user's password in the response
```

### Subtasks
1. **Define the Endpoint**
  - [ ] Create the endpoint to edit account profile information.
  - [ ] Ensure the endpoint requires JWT access and CSRF tokens.
2. **Token Validation**
  - [ ] Implement JWT access token validation.
  - [ ] Implement CSRF token validation.
3. **Data Validation**
  - [ ] Validate the editing information provided by the user (e.g., unique email, unique fiscal code, valid birth date format).
4. **Update User Information**
  - [ ] Update the user's personal information in the database.
  - [ ] Ensure the user's password is not shown in the response.
5. **Response Formatting**
  - [ ] Format the updated personal information in JSON
6. **Error Handling**
 - [ ] Implement error handling for invalid or missing tokens.
 - [ ] Implement error handling for invalid editing information.
 - [ ] Ensure appropriate error messages are returned for each type of invalid or missing token and invalid data.
7. **Testing** 
  - [ ] Write unit tests for the endpoint.
  - [ ] Write integration tests for the entire process, including token validation, data validation, and information update.
  - [ ] Test all acceptance criteria scenarios to ensure compliance.
