### ISSUE TITLE
Patient Change Password

### ISSUE THREAD

**Issue by Kisuk3S4m** [Kisuk3S4m/jungle-ehr-api#6]
**As** logged-in patient,
**I want** to modify my account password,
**So** I could change the old password with the new one.

### Details and assumptions
- Users must provide an old password and a new password to the created API endpoint.
- Users must repeat the new password, and it must match the initially provided new password.
- Users must also provide JWT access and CSRF tokens to the endpoint. If these are missing or invalid, the endpoint should reject the operation.
- The endpoint should log out the user from the current session, requiring users to re-authenticate to continue using the application, if the old password is correct and the new passwords are matched.

### Acceptance Criteria
```gherkin
Given the user is logged in
And the user provides valid JWT access and CSRF tokens
And the user provides the correct old password
And the user provides a new password and repeats it correctly
When the user requests to modify their password
Then the system should update the user's password
And the system should log out the user from the current session
And the system should require the user to re-authenticate to continue using the application
```

```gherkin
Given the user is logged in
And the user provides an invalid JWT access token
When the user requests to modify their password
Then the system should reject the request
And the system should return an error message indicating an invalid token
```

```gherkin
Given the user is logged in
And the user provides an invalid CSRF token
When the user requests to modify their password
Then the system should reject the request
And the system should return an error message indicating an invalid token
```

```gherkin
Given the user is logged in
And the user does not provide a JWT access token
When the user requests to modify their password
Then the system should reject the request
And the system should return an error message indicating a missing token
```

```gherkin
Given the user is logged in
And the user does not provide a CSRF token
When the user requests to modify their password
Then the system should reject the request
And the system should return an error message indicating a missing token
```

```gherkin
Given the user is logged in
And the user provides valid JWT access and CSRF tokens
And the user provides an incorrect old password
When the user requests to modify their password
Then the system should reject the request
And the system should return an error message indicating the old password is incorrect
```

```gherkin
Given the user is logged in
And the user provides valid JWT access and CSRF tokens
And the user provides a new password and repeats it incorrectly
When the user requests to modify their password
Then the system should reject the request
And the system should return an error message indicating the new passwords do not match
```

### Subtasks
1. **Define the Endpoint**
- [ ] Create the endpoint to modify the account password.
- [ ] Ensure the endpoint requires JWT access and CSRF tokens.

2. **Token Validation**
 - [ ] Implement JWT access token validation.
 - [ ] Implement CSRF token validation.

3.**Password Validation**
- [ ] Validate the old password provided by the user.
- [ ] Ensure the new password and its repetition match.
- [ ] Ensure the new password meets security requirements (length, complexity, etc.).

4. **Update Password**
- [ ] Update the user's password in the database.
- [ ] Log out the user from the current session.

5. **Session Management**
- [ ] Invalidate the current user session.
- [ ] Ensure the user is required to re-authenticate.

6. **Response Formatting**
- [ ] Format the response in JSON.
- [ ] Ensure appropriate messages are returned for success and error scenarios.

7. **Error Handling**
- [ ] Implement error handling for invalid or missing tokens.
- [ ] Implement error handling for incorrect old passwords and non-matching new passwords.
- [ ] Ensure appropriate error messages are returned for each scenario.

8. **Testing**
- [ ] Write unit tests for the endpoint.
- [ ] Write integration tests for the entire process, including token validation, password validation, and password update.
- [ ] Test all acceptance criteria scenarios to ensure compliance.
